### ISSUE TITLE
vue3 使用会提示栈溢出

### ISSUE THREAD

**Issue by XiaoLi-sach** [Tencent/vConsole#469]
vConsole Version: 3.9.4
vue3 使用会提示栈溢出导致很多问题
![image](https://user-images.githubusercontent.com/55753927/139783239-7d3b8867-6511-4f7b-9719-c04017f6e999.png)

**Comment by starlet0822** [comment]
同样问题，官网好像不维护这个插件了

**Comment by XiaoLi-sach** [comment]
我现在在用 eruda 代替

**Comment by Maizify** [comment]
@XiaoLi-sach 请问如何复现？

**Comment by Maizify** [comment]
@starlet0822 有在维护的。

**Comment by XiaoLi-sach** [comment]
@Maizify  按文档的使用方法引用后， 就会出现了

**Comment by XiaoLi-sach** [comment]
@Maizify  按文档的使用方法引用后， 就会出现了

**Comment by Maizify** [comment]
@XiaoLi-sach 我怀疑是你的业务代码里，有一些变量会触发这个 error，因为我不知道是怎样的东西，构造不出来，就不太好修。

**Comment by XiaoLi-sach** [comment]
@Maizify  我是在index.html 中 添加了这样一段
``` js
<script type="text/javascript" src="./AppBridge.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/vConsole/3.9.0/vconsole.min.js"></script>
<script>
      let vConsole = new VConsole();
      appBridge.InvokeApp('HideLoading',[]);
</script>
```
然后 npm 也install 了一下 vconsole
这样添加的， 然后页面中， 只使用了ref

**Comment by Maizify** [comment]
@XiaoLi-sach 可否提供导致报错的那个log及其对应的变量？

**Comment by zhangyuang** [comment]
@XiaoLi-sach 有最简复现吗

**Comment by XiaoLi-sach** [comment]
@Maizify @zhangyuang  这个报错的时候我就改用其他的了，我再新建项目引用就没问题了， 应该是因为业务代码导致的么？

**Comment by zhangyuang** [comment]
我这边无法复现，肯定要提供最简复现才能查问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: XiaoLi_1456 ***@***.***&gt;
发送时间: 2021年11月6日 14:22
收件人: Tencent/vConsole ***@***.***&gt;
抄送: yuuang ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[Tencent/vConsole] vue3 使用会提示栈溢出 (Issue #469)





 
@Maizify @zhangyuang  这个报错的时候我就改用其他的了，我再新建项目引用就没问题了， 应该是因为业务代码导致的么？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XiaoLi-sach** [comment]
@zhangyuang  我查一下我的业务代码

**Comment by Maizify** [comment]
@XiaoLi-sach 可能是的。因为先前也有用户反馈过类似的问题，但我都无法复现。vConsole内有风险的地方都有try catch，按理说不会报这类错误。由于 vconsole 劫持了 console.error，所以在 chrome 里会看到 error 由 vconsole.min.js 发出，所以很多开发者会误以为是 vConsole 的问题。但也不排除是某些机制导致 vConsole 会触发 vue error，所以还是需要具体情况具体分析。

**Comment by XiaoLi-sach** [comment]
@Maizify  我觉得是这样， 触发这个错误后， 我引用的vant 组件一系列操作都执行不了， 给vConsole 删掉就可以了， 报错提示也是vConsole 给的， 就觉得是vConsole 的问题， 我再新建项目尝试去复现， 却复现不出来。 我看看我当时的业务代码是怎么写的。

**Comment by Maizify** [comment]
@XiaoLi-sach 如果后续能复现，请发一下，我也对这个报错很好奇。

**Comment by SailorCai** [comment]
我也遇到这个问题，想过用eruda代替，但是eruda问题更多
项目从vue2升级到vue3后出现这个问题，但是并不是所有报错都会导致溢出，而是某一类报错出现的问题，下面的报错就导致了溢出：
DropSelect.vue?f5af:186 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Proxy.beforeUnmount (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/list/components/base/DropSelect.vue?vue&type=script&lang=js:144:29)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6824:22)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6833:21)
    at Array.hook.__weh.hook.__weh (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2123:29)
    at invokeArrayFns (webpack-internal:///./node_modules/@vue/runtime-core/node_modules/@vue/shared/dist/shared.esm-bundler.js:601:15)
    at unmountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4920:79)
    at unmount (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4830:13)
    at unmountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4958:13)
    at unmount (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4848:17)
    at unmountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4929:13)

以上报错出现的同时如果开启了vconsole就会导致调用栈溢出，而出现上面报错之前还报了另外一个错，这个错却不会导致溢出：
index.vue?f736:507 Uncaught (in promise) TypeError: _this2.searchShenceReport is not a function
    at eval (index.vue?f736:507)

具体麻烦官方各位同学看一下能不能定位出来，谢谢

**Comment by SailorCai** [comment]
感觉应该是和vue3的proxy机制有关系

**Comment by Maizify** [comment]
目前我正在重构vConsole，其中重写了Log相关逻辑，有可能会对这一现象有所改善（因为无法准确复现，所以只能这么说）。
预计将在v3.10.0版本发布，如果有兴趣的话，可以用Github上`dev`分支的v3.10.0-rc版本看看是否还会复现，这对我们很有帮助。

**Comment by SailorCai** [comment]
稍后我试一下rc版本看下问题是否解决

**Comment by SailorCai** [comment]
有v3.10.0-rc版本的cdn地址吗？

**Comment by Maizify** [comment]
> 有v3.10.0-rc版本的cdn地址吗？

还在持续开发中，还没有发布到npm。目前这一版dev分支是可以build通过的，可以先自己build下？

**Comment by liujianya371** [comment]
![image](https://user-images.githubusercontent.com/4703288/145188169-f507b061-0f9b-4880-bdc8-03eba7844032.png)

RangeError: Maximum call stack size exceeded
    at console.window.console.<computed> [as warn] (vconsole.min.js:formatted:954)
    at warn (runtime-core.esm-bundler.js?5c40:38)
    at Object.PublicInstanceProxyHandlers.ownKeys (runtime-core.esm-bundler.js?5c40:6935)
    at Function.getOwnPropertyNames (<anonymous>)
    at f (vconsole.min.js:formatted:139)
    at Object.e.JSONStringify (vconsole.min.js:formatted:206)
    at VConsoleDefaultTab.value (vconsole.min.js:formatted:1017)
    at console.window.console.<computed> (vconsole.min.js:formatted:954)
    at t.value (vconsole.min.js:formatted:988)
    at t.value (vconsole.min.js:formatted:1026)
    
    vue3.0  遇到了。

**Comment by Maizify** [comment]
主要是Vue的Proxy引起的。vConsole 3.10.0里重写了相关逻辑，应该不会再出现 `Object.PublicInstanceProxyHandlers.ownKeys` 引起的死循环问题了。

**Comment by HuangMou0828** [comment]
vue2在computed中打印this（且该computed在template中使用）,就会出现这个情况
