### ISSUE TITLE
uniapp app端,接入vConsole报错

### ISSUE THREAD

**Issue by hootigger** [Tencent/vConsole#629]
vConsole Version:
3.15.1

<img width="1370" alt="image" src="https://github.com/Tencent/vConsole/assets/23418191/96cb6882-2aa2-4af0-b28d-8fb0561afbf2">

vue3 + ts + vite

main.ts 引入
```
export function createApp() {
  const app = createSSRApp(App)
  app.use(new VConsole() as any)
  app.use(uviewPlus)
  setupStore(app)
  return {
    app,
  }
}
```

也尝试过vite-plugin-vconsole插件 一样的错误.

**Comment by Maizify** [comment]
你的环境里没有 `window.navigator.sendBeacon` 导致的报错。我查了下，应该是上次的兼容没做全，有遗漏，导致某些地方还是会去读不存在的 navigator。我再fix下。

**Comment by hootigger** [comment]
感谢这么快响应, 等修复后,我再测下.

**Comment by hootigger** [comment]
尝试clone build后发现又有新的问题了, 是不是app端由于是weex实现,没有window这些基础对象,所以导致uniapp app端的时候是无法使用的?

**Comment by Maizify** [comment]
没有`window`对象那肯定用不了的了，`window.console, window.XMLHttpRequest, window.localStorage, window.requestAnimationFrame`都是依赖window的。

**Comment by himotou** [comment]
`reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'MutationObserver' of undefined
 at _ (app-service.js:4866:26)`

是报这个问题吗，
我clone build后报这个问题。

**Comment by bluefantasy728** [comment]
> vConsole Version: 3.15.1
> 
> <img alt="image" width="1370" src="https://user-images.githubusercontent.com/23418191/245657139-96cb6882-2aa2-4af0-b28d-8fb0561afbf2.png">
> vue3 + ts + vite
> 
> main.ts 引入
> 
> ```
> export function createApp() {
>   const app = createSSRApp(App)
>   app.use(new VConsole() as any)
>   app.use(uviewPlus)
>   setupStore(app)
>   return {
>     app,
>   }
> }
> ```
> 
> 也尝试过vite-plugin-vconsole插件 一样的错误.

真心求教，你后来解决了吗？我最近想用uniapp开发APP，连的xcode的iphone模拟器，一时不知道如何调试，本来以为通过safari的开发里可以，谁知道每次只要重新修改代码，热启动的时候，safari的调试窗口就消失了，而hbuilder里也打印不出对象，全部是[object Object]，那这样岂不是摸瞎开发？你这边有什么其他方案调试样式和js代码吗？感谢

**Comment by hootigger** [comment]
> > vConsole Version: 3.15.1
> 
> > 
> 
> > <img alt="image" width="1370" src="https://user-images.githubusercontent.com/23418191/245657139-96cb6882-2aa2-4af0-b28d-8fb0561afbf2.png">
> 
> > vue3 + ts + vite
> 
> > 
> 
> > main.ts 引入
> 
> > 
> 
> > ```
> 
> > export function createApp() {
> 
> >   const app = createSSRApp(App)
> 
> >   app.use(new VConsole() as any)
> 
> >   app.use(uviewPlus)
> 
> >   setupStore(app)
> 
> >   return {
> 
> >     app,
> 
> >   }
> 
> > }
> 
> > ```
> 
> > 
> 
> > 也尝试过vite-plugin-vconsole插件 一样的错误.
> 
> 
> 
> 真心求教，你后来解决了吗？我最近想用uniapp开发APP，连的xcode的iphone模拟器，一时不知道如何调试，本来以为通过safari的开发里可以，谁知道每次只要重新修改代码，热启动的时候，safari的调试窗口就消失了，而hbuilder里也打印不出对象，全部是[object Object]，那这样岂不是摸瞎开发？你这边有什么其他方案调试样式和js代码吗？感谢

后面由于着急进度.就没有继续研究，如果你是unisdk接入的话.可以在option开启log，然后还需要加入log的库，uni文档上有，然后在xcode控制台可以看到日志了，就是调试比较麻烦，需要打包wgt，cp到工程，我一般是用微信开发者工具调试，后面再去app看

**Comment by zhanglxny** [comment]
@hootigger vite-plugin-vconsole 引入没有起任何作用

**Comment by bk13699** [comment]
> نسخه vConsole: 3.15.1
> 
> <img alt="تصویر" width="1370" src="https://private-user-images.githubusercontent.com/23418191/245657139-96cb6882-2aa2-4af0-b28d-8fb0561afbf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTY0MTMsIm5iZiI6MTcwMjI5NjExMywicGF0aCI6Ii8yMzQxODE5MS8yNDU2NTcxMzktOTZjYjY4ODItMmFhMi00YWYwLWIyOGQtOGZiMDU2MWFmYmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTgxOGNmZGMyNzE1OWU5N2NjZGE1ZjFkNzU5MWM1NTVmNTcwNDM1NjcwN2Q5ZTE2YTJjNDNmN2NhOWNlY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JVUEOSe-Rsv_W_HAnRk-5FLIm7hKdWSW8HXVRUXUUe4">
> vue3 + ts + vite
> 
> main.ts 引入
> 
> ```
> export function createApp() {
>   const app = createSSRApp(App)
>   app.use(new VConsole() as any)
>   app.use(uviewPlus)
>   setupStore(app)
>   return {
>     app,
>   }
> }
> ```
> 
> 也尝试过vite-plugin-vconsole插件 一样的错误.

https://github.com/Tencent/vConsole/issues/629#issue-1755925006****

**Comment by zhanglxny** [comment]
您好，来信收到，我会尽快回复

**Comment by luo119** [comment]
> 您好，来信收到，我会尽快回复

请尽快处理，哎，我也遇到了

**Comment by Mr-LiuDC** [comment]
uniapp app端 vue3 + ts + vite，还是不行啊，报一样的问题，

安卓：
```
17:05:27.952 正在同步手机端程序文件...
17:05:30.058 同步手机端程序文件完成
17:05:32.522 You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
17:05:32.990 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'sendBeacon' of undefined
 at  (app-service.js:21555:41)
 at  (app-service.js:23213:10)
 at  (app-service.js:23214:8)
 at  (app-service.js:15277:24)
 at  (app-service.js:15278:6)
 at  (app-service.js:23216:5)
 at  (app-service.js:23237:3)
```



iOS：
```
17:05:32.969 同步手机端程序文件完成
17:05:34.530 You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle. __WARN
```
