### ISSUE TITLE
当我使用VConsole.destory销毁实例后会在控制台出现报错

### ISSUE THREAD

**Issue by nice-wwming** [Tencent/vConsole#649]
vConsole Version:3.15.1
报错详细内容：
Uncaught TypeError: Cannot read properties of undefined (reading 'update')
    at u2 (vconsole.min.js:10:91405)
    at e2._flushLogs (vconsole.min.js:10:91641)
    at vconsole.min.js:10:91147

**Comment by shunia** [comment]
果然是个老问题：https://github.com/Tencent/vConsole/issues/587 
真巧咱俩最近都遇到了，我翻了一下源代码，应该是因为`log.model`里面的限流逻辑`window.requestAnimationFrame`的回调方法`_flushLogs`里面的代码导致的。

我的log是一个interval性质的，调用destroy之后，`log.model`的`unbind`方法没有正确的屏蔽掉限流逻辑，但是又把`Store`里的东西删了，导致限流回调触发后可能会去获取`Store`里面的内容，但是获取的代码没做空保护，从而触发报错了。

这个改动的方法很多，比如在`unbind`的时候清空`logQueue`，比如增加一个flag来阻止限流回调的运行同时阻止`addLog`的执行，比如在限流回调中获取`store`的时候加一个空保护。

做一个空保护是最简单的，但是从代码设计的角度来说也许不是最优的。

**Comment by shunia** [comment]
> 



> 果然是个老问题：#587 真巧咱俩最近都遇到了，我翻了一下源代码，应该是因为`log.model`里面的限流逻辑`window.requestAnimationFrame`的回调方法`_flushLogs`里面的代码导致的。
> 
> 我的log是一个interval性质的，调用destroy之后，`log.model`的`unbind`方法没有正确的屏蔽掉限流逻辑，但是又把`Store`里的东西删了，导致限流回调触发后可能会去获取`Store`里面的内容，但是获取的代码没做空保护，从而触发报错了。
> 
> 这个改动的方法很多，比如在`unbind`的时候清空`logQueue`，比如增加一个flag来阻止限流回调的运行同时阻止`addLog`的执行，比如在限流回调中获取`store`的时候加一个空保护。
> 
> 做一个空保护是最简单的，但是从代码设计的角度来说也许不是最优的。

更正一下触发的原因，并不是因为`interval性质的`log导致的，**而是在destroy之前打一条log就可以必现这个报错**。

**Comment by suzhenghui-sky** [comment]
我也有类似的问题；VConsole.destory； 版本： "vconsole": "^3.15.0",；   Uncaught TypeError: can't access property "update", s.O.get(...) is undefined
    u2 vconsole.min.js:10
    _flushLogs vconsole.min.js:10
    _signalLog vconsole.min.js:10
    _signalLog vconsole.min.js:10
    addLog vconsole.min.js:10
    node_modules/vconsole/dist/vconsole.min.js/</5629/e2._mockConsoleLog/</window.console[n3]< vconsole.min.js:10
    closeVConsole use-console-debug.ts:21
    onDebugEnable system-settings-page-body.vue:111
    setTimeout handler*onDebugEnable system-settings-page-body.vue:110
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:176
    emit runtime-core.esm-bundler.js:664
    onClick quasar.esm.js:7719
    callWithErrorHandling runtime-core.esm-bundler.js:158
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    invoker runtime-dom.esm-bundler.js:278
    addEventListener runtime-dom.esm-bundler.js:233
    patchEvent runtime-dom.esm-bundler.js:247
    patchProp runtime-dom.esm-bundler.js:310
    mountElement runtime-core.esm-bundler.js:5209
    processElement runtime-core.esm-bundler.js:5156
    patch runtime-core.esm-bundler.js:5028
    componentUpdateFn runtime-core.esm-bundler.js:5708
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    setupRenderEffect runtime-core.esm-bundler.js:5822
    mountComponent runtime-core.esm-bundler.js:5612
    processComponent runtime-core.esm-bundler.js:5565
    patch runtime-core.esm-bundler.js:5040
    mountChildren runtime-core.esm-bundler.js:5284
    mountElement runtime-core.esm-bundler.js:5191
    processElement runtime-core.esm-bundler.js:5156
    patch runtime-core.esm-bundler.js:5028
    componentUpdateFn runtime-core.esm-bundler.js:5708
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    setupRenderEffect runtime-core.esm-bundler.js:5822
    mountComponent runtime-core.esm-bundler.js:5612
    processComponent runtime-core.esm-bundler.js:5565
    patch runtime-core.esm-bundler.js:5040
    mountChildren runtime-core.esm-bundler.js:5284
    mountElement runtime-core.esm-bundler.js:5191
    processElement runtime-core.esm-bundler.js:5156
    patch runtime-core.esm-bundler.js:5028
    componentUpdateFn runtime-core.esm-bundler.js:5708
    run reactivity.esm-bundler.js:178
[vconsole.min.js:10:91179](https://localhost:9000/node_modules/vconsole/dist/vconsole.min.js)

**Comment by suzhenghui-sky** [comment]
> > 
> 
> > 果然是个老问题：#587 真巧咱俩最近都遇到了，我翻了一下源代码，应该是因为`log.model`里面的限流逻辑`window.requestAnimationFrame`的回调方法`_flushLogs`里面的代码导致的。
> > 我的log是一个interval性质的，调用destroy之后，`log.model`的`unbind`方法没有正确的屏蔽掉限流逻辑，但是又把`Store`里的东西删了，导致限流回调触发后可能会去获取`Store`里面的内容，但是获取的代码没做空保护，从而触发报错了。
> > 这个改动的方法很多，比如在`unbind`的时候清空`logQueue`，比如增加一个flag来阻止限流回调的运行同时阻止`addLog`的执行，比如在限流回调中获取`store`的时候加一个空保护。
> > 做一个空保护是最简单的，但是从代码设计的角度来说也许不是最优的。
> 
> 更正一下触发的原因，并不是因为`interval性质的`log导致的，**而是在destroy之前打一条log就可以必现这个报错**。

是的，我把关闭之前的log关了就不报错了。感谢

**Comment by liesauer** [comment]
我丢，又是中国的kpi项目吗，就是一句简单的`destroy()`都能报错几年没修复？？？

**Comment by liesauer** [comment]
> 是的，我把关闭之前的log关了就不报错了。感谢

请问如何将log关了

**Comment by Maizify** [comment]
感谢反馈！根本原因是竞态：`console.log()` 会通过 `requestAnimationFrame` 异步调度日志刷新，但如果此前 `destroy()` 已执行并删除了 store，rAF 回调触发时 `store.update()` 就会报错。

已在即将发布的 3.16.0 中修复，方式是在 `_flushLogs()` 里对 store 做空判断。
